trigger:
- master

variables:
  dockerImage: kumojin/caddy

strategy:
  matrix:
    linux:
      imageName: ubuntu-16.04
      dockerTag: linux
    windows:
      imageName: win1803
      dockerTag: windows

pool:
  vmImage: $(imageName)

steps:
- script: docker build -f Dockerfile.$(dockerTag) -t $(dockerImage):$(dockerTag) .
  displayName: Docker build

- script: docker login  -u $(dockerId) -p $(dockerPassword)
  displayName: Docker registry login

- script: docker push $(dockerImage):$(dockerTag) 
  displayName: Docker push image to registry
