trigger:
- master

variables:
  dockerImage: kumojin/caddy

strategy:
  matrix:
    linux:
      poolName: Hosted Ubuntu 1604
      dockerTag: linux
    windows:
      poolName: Julien Laptop
      dockerTag: windows

pool:
  name: $(poolName)

steps:
- script: docker build -f Dockerfile.$(dockerTag) -t $(dockerImage):$(dockerTag) .
  displayName: Docker build

- script: docker login  -u $(dockerId) -p $(dockerPassword)
  displayName: Docker registry login

- script: docker push $(dockerImage):$(dockerTag) 
  displayName: Docker push image to registry
